# -*- coding: utf-8 -*-
"""K-Means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1immWCRRy9bINwlOP6P03FpAl8VV4vYMn
"""

import pandas as pd
import matplotlib.pyplot as plt

uci_path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00292/Wholesale%20customers%20data.csv'
df = pd.read_csv(uci_path, header=0)

print(df.head())
print('\n')

print(df.info())
print('\n')

print(df.describe())

X = df.iloc[:, :]
print(X[:5])
print('\n')

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit_transform(X)

print(X[:5])

from sklearn import cluster

kmeans = cluster.KMeans(init='k-means++',n_clusters=5, n_init=10)

kmeans.fit(X)

cluster_label = kmeans.labels_
print(cluster_label)
print('\n')

df['Cluster'] = cluster_label
print(df.head())

df.plot(kind='scatter', x='Grocery', y='Frozen', c='Cluster', cmap='Set1', colorbar=False, figsize=(10, 10))
df.plot(kind='scatter', x='Milk', y='Delicassen', c='Cluster', cmap='Set1', colorbar=True, figsize=(10, 10))
plt.show()

mask = (df['Cluster'] == 0) | (df['Cluster'] == 4)
ndf = df[~mask]
ndf.plot(kind='scatter', x='Grocery', y='Frozen', c='Cluster', cmap='Set1', colorbar=False, figsize=(10, 10))
ndf.plot(kind='scatter', x='Milk', y='Delicassen', c='Cluster', cmap='Set1', colorbar=True, figsize=(10, 10))
plt.show()